.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE, .pullapprove.yml, README.md, package.json
following add to this PR :- 
* GH pages deployment by Circle CI (GH pages publish using _git-gdp access token_)
* add PR template
* README update seek-oss -> seekinternational ; seek-style -> seek-asia-style
=> Style guide deployment

.circleci/config.yml
What does this PR do?
---------------------
To fix circleci config and to have status check for PR before merging
How can I test this?
--------------------
Not required.  Just login to circleci view master and rest of branch able to build by commit trigger
=> Test gh deploy

docs/src/components/App/App.js, docs/src/components/App/Header/Header.css.js, docs/src/components/App/Header/Header.js, docs/src/components/App/Header/Logo/Logo.js, react/Button/Button.css.js, react/Button/Button.js, react/Button/Button.test.js, react/Button/__snapshots__/Button.test.js.snap, react/JobCard/JobCard.css.js, react/JobCard/JobCard.demo.js, react/JobCard/JobCard.js, react/JobCard/JobCard.test.js, test/jest.config.json
Our tests couldn't interpret css-in-js, which is why the snapshots were wrong.  We also need to lint more :)
=> chore(tests): lint and support css-in-js

.circleci/config.yml
This should cause a new npm package to be generated whenever we merge to master
=> chore(ci): add semantic-release

react/Checkbox/Checkbox.demo.js, react/Checkbox/Checkbox.js, react/Checkbox/Checkbox.less, react/Checkbox/Checkbox.test.js, react/Checkbox/__snapshots__/Checkbox.test.js.snap
To support new option "position" in checkbox control
REASON FOR CHANGE:
To support right-hand-side checkbox design
=> feat(checkbox): option - position

README.md
Updates readme to better reflect this repo and project.
Removed references to things that currently won't work or aren't useful to SEEK Asia
=> chore(docs): make readme more appropriate for SEEK Asia

react/Button/Button.demo.js, react/ButtonGroup/ButtonGroup.demo.js, react/Footer/Footer.demo.js, react/Header/Header.demo.js, react/JobCard/JobCard.demo.js, react/LogoRainbow/LogoRainbow.less
Fix all component still import seek-style-guide
{{ Description of breaking API change }}
RFC URL:
{{ URL of associated RFC for API change }}
Before:
```js
{{ Old code }}
```
After:
```js
{{ New code }}
```
EXAMPLE USAGE:
```js
{{ Code }}
```
=> fix(package): Fix all component still import seek-style-guide

react/JobCard/JobCard.js, react/JobCard/__snapshots__/JobCard.test.js.snap
Update job title to correct font type.
-
RFC URL:
-
Before:
```js
{{ Old code }}
```
After:
```js
{{ New code }}
```
EXAMPLE USAGE:
```js
{{ Code }}
```
=> feat(JobCard): Update job title font

react/Checkbox/Checkbox.less, react/JobCard/JobCard.demo.js, react/JobCard/JobCard.js, react/JobCard/__snapshots__/JobCard.test.js.snap
updated the checkbox style only
=> update the checkbox style

react/JobCard/JobCard.less
Enhance jobcard to allow user see more description
No
RFC URL:
No
Before:
```js
{{ Old code }}
```
After:
```js
{{ New code }}
```
EXAMPLE USAGE:
```js
{{ Code }}
```
=> feat(jobCard): remove 2 lines limited of description

.gitignore, react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/__snapshots__/JobCard.test.js.snap
Adjust company text padding
n/a
RFC URL:
{{ URL of associated RFC for API change }}
Before:
```js
{{ Old code }}
```
After:
```js
{{ New code }}
```
EXAMPLE USAGE:
```js
{{ Code }}
```
=> feat(JobCard): Adjust title padding

react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/__snapshots__/JobCard.test.js.snap
UI refinement
No
RFC URL:
No
Before:
```js
{{ Old code }}
```
After:
```js
{{ New code }}
```
EXAMPLE USAGE:
```js
{{ Code }}
```
=> fix(jobCard): add space to jobinfo list and post duration

jobStreet/Header/links.js
=> fix(Header): Unbold company profile link

react/JobCard/JobCard.demo.js, react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/JobCard.test.js, react/JobCard/__snapshots__/JobCard.test.js.snap, react/NavigationBar/NavigationBar.less, react/NavigationBar/__snapshots__/NavigationBar.test.js.snap
Highlight company name for keyword search
=> feat(JobCard): Highlight keyword on company

react/JobCard/JobCard.less
=> fix(jobCard): long title exceed card border

docs/src/demoSpecs.js, react/JobCardLoader/JobCardLoader.demo.js, react/JobCardLoader/JobCardLoader.js, react/JobCardLoader/JobCardLoader.less, react/JobCardLoader/JobCardLoader.test.js, react/JobCardLoader/__snapshots__/JobCardLoader.test.js.snap, react/index.js
Add JobCard Content Placeholder - new loader
nope
=> feat(JobCardLoader): Add JobCard content placeholder - loader

jobStreet/Footer/footer.less
Trying to release again to NPM.
BREAKING CHANGE: N/A
RFC URL: N/A
MIGRATION GUIDE: N/A
=> feat(JobStreet/Header): Release JobStreet Header with working links

react/Checkbox/Checkbox.demo.js, react/Checkbox/Checkbox.demo.less, react/Checkbox/Checkbox.js, react/Checkbox/Checkbox.less, react/Checkbox/Checkbox.test.js, react/Checkbox/__snapshots__/Checkbox.test.js.snap
Add fullwidth option,
Improved checkbox color scheme
EXAMPLE USAGE:
```js
<Checkbox fullWidth />
```
=> feat(checkbox): Add fullwidth option & change checkbox style

docs/server.js, docs/src/components/App/App.js, docs/src/components/App/Header/Header.css.js, react/Button/Button.js
In SRP-react `process.env.SKU_TENANT` is deprecated. 
Update tenant - from `process.env.SKU_TENANT` to `process.env.APP_TENANT`;
`process.env.SKU_TENANT` is deprecated,  use `process.env.APP_TENANT` instead
=> fix(tenant): Update tenant node env

react/Header/components/Menu/Menu.less
fix the scroll issue for the header menu
=> fix(Header): fix the scroll issue for the header menu in mobile view

react/Checkbox/Checkbox.js, react/Checkbox/Checkbox.less
Remove space between label and extraLabel
=> fix(Checkbox): Remove space between label and extraLabel

react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/__snapshots__/JobCard.test.js.snap, react/Strong/Strong.less
- Fix broken highlighted style
- Update design
N/A
=> fix(JobCard): update design

react/Checkbox/Checkbox.less, react/Header/components/Menu/components/MenuItem/MenuItem.js, react/Header/components/Menu/components/MenuItem/__snapshots__/MenuItem.test.js.snap
UI update on filters require them to change colors
RFC URL:
https://trello.com/c/Sb3oFda1/558-design-applying-new-button-style-to-srp-desktop-filter-design
=> Checkbox update

react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
=> fix(updateSnapshot): update snap shot

react/TitledCard/TitledCard.demo.js, react/TitledCard/TitledCard.js, react/TitledCard/TitledCard.less, react/TitledCard/TitledCard.sketch.js, react/TitledCard/TitledCard.test.js, react/TitledCard/__snapshots__/TitledCard.test.js.snap, react/index.js
As we discuss in `seek-asia-style-guide` channel, adding a new component name `Titled Card`
none
RFC URL:
none
none
EXAMPLE USAGE:
```
import {
TitledCard,
Text
} from 'seek-asia-style-guide/react';
<TitledCard text="Title">
<Text>
This is some text inside a card.
</Text>
</TitledCard>
```
Print Screen:
=> Add a new component TitledCard

react/ListItem/ListItem.demo.js, react/ListItem/ListItem.js, react/ListItem/ListItem.less, react/ListItem/ListItem.sketch.js
List item should not have hover state as default, therefore create an extra prop as feature trigger
EXAMPLE USAGE:
```js
<ListItem value="Description" hvHover />
```
=> feat(listitem): add optional hover prop

react/ShowMore/ShowMore.demo.js, react/ShowMore/ShowMore.js, react/ShowMore/ShowMore.sketch.js, react/ShowMore/__snapshots__/ShowMore.test.js.snap
facing some problem in `srp-react` found out there is an extra section in showMore component
remove some the section in showMore, change the props from component to children
RFC URL:
{{ URL of associated RFC for API change }}
Before:
```
import {
ShowMore,
Card,
Section,
Text
} from 'seek-asia-style-guide/react';
<ShowMore showLessHeight={100} component={
<Card>
<Section>
<Text shouting>
At jobsDB, we believe in an open and inclusive world for all.
</Text>
<Text>
Here, opportunities and possibilities are plenty: A fresh start. A new career.
<br />
A welcome change. These are just a few of the things we help people explore.
<br />
As a leading job portal with …
```
=> Remove component props and section

react/JobCard/components/ShelfSection/ShelfSection.js
Fix: `TypeError: reduce of empty array with no initial value` which breaks srp app, and cause `504`
=> fix(ShelfSection): fix reduce of empty array with no initial value

react/JobCard/JobCard.js, react/JobCard/JobCard.test.js, react/JobCard/__snapshots__/JobCard.test.js.snap
Remove unwanted `more`/`less` button when there are no shelf links.
BREAKING CHANGE: N/A
RFC URL: N/A
=> fix(JobCard): remove more/less button when there are no shelf links

react/index.js
=> fix(SplitView): fixed import

react/JobCard/JobCard.demo.js, react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/JobCard.test.js, react/JobCard/JobCardPropTypes.js, react/JobCard/__snapshots__/JobCard.test.js.snap
adding branded ad design into job card [trello card](https://trello.com/c/hboeq04X/539-brandedad-job-card-design-concept-for-ba-and-sol)
- During desktop view it will only show when it is not split view
- During mobile view it will show on top of job title.
nope, just added two new props `enableBrandedAd` and `bannerUrl`
RFC URL:
none
none, just added two new props `enableBrandedAd` and `bannerUrl`
EXAMPLE USAGE:
```
<JobCard
enableBrandedAd
isVariation
job={{
bannerUrl: 'https://content.jobsdbcdn.com/Content/CmsContent/Logo/HK/JobsDBFiles/CompanyLogo/banner-m/34999m.png',
careerLevel: 'Entry Level',
company: {
link: '/jobCard',
name: 'SEEK Asia',
title: 'Jobs at …
```
=> feat(branded ad): adding branded ad design into job card

react/JobCard/JobCard.js, react/JobCard/JobCard.less, react/JobCard/__snapshots__/JobCard.test.js.snap
update the job description position in the job card
[trello card](https://trello.com/c/b42az37S/677-brandedad-include-job-description-in-list-view-job-card)
=> fix(jobCard): update the job desc position

react/JobCard/components/ShelfButton/ShelfButton.js, react/JobCard/components/ShelfButton/__snapshots__/ShelfButton.test.js.snap
JobCard in mobile isn't showing Date Posted. That's not great.
Run this branch locally, then check out JobCard. Make sure when you change the viewport to mobile that the datePosted still exists.
=> fix(JobCard): Show posted date on Mobile

react/Header/Header.js, react/Header/Header.less, react/Header/Header.test.js, react/Header/__snapshots__/Header.test.js.snap, react/Header/components/Menu/Menu.js, react/Header/components/Menu/Menu.less, react/Header/components/Menu/Menu.test.js, react/Header/components/Menu/__snapshots__/Menu.test.js.snap
In mobile view : 
- Add hamburger bar toggle
- Add space on top of menu when it trigger from top hamburger bar toggle
New:
Old:
=> fix(Header): Add mobile menu space

react/Hidden/Hidden.demo.js, react/Hidden/Hidden.sketch.js
Add back demo page for `<Hidden />` component
=> fix(docs): Add docs for hidden component
